CREATE TABLE DEBATER(	
	DEB_ID decimal(16) PRIMARY KEY NOT NULL,
	NAME varchar2(128) NOT NULL,
	TEA_ID decimal(16) NOT NULL, 
	DATE_OF_BIRTH timestamp,
	ADDRESS varchar2(64),
	TELEPHONE_NO varchar2(32),
	DATE_FROM timestamp NOT NULL,
	DATE_UNTIL timestamp NOT NULL,
	USER_LOCK timestamp NOT NULL);

CREATE TABLE TEAM(	
	TEA_ID decimal(16) PRIMARY KEY NOT NULL,
	INSTITUTION varchar2(64),
	TEAM_NAME varchar2(64) NOT NULL,
	TEAM_NAME_SHORT varchar2(64) NOT NULL,
	DATE_FROM timestamp NOT NULL,
	DATE_UNTIL timestamp NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE JUDGE(	
	JUD_ID decimal(16) PRIMARY KEY NOT NULL,
	NAME varchar2(128) NOT NULL,
	DATE_OF_BIRTH timestamp,
	ADDRESS varchar2(128),
	TELEPHONE_NO varchar2(32),
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE FORBIDDEN_JUDGE(	
	FOR_JUD_ID decimal(16) PRIMARY KEY NOT NULL,
	JUD_ID decimal(16) NOT NULL,
	TEA_ID decimal(16) NOT NULL,
	DATE_FROM timestamp NOT NULL,
	DATE_UNTIL timestamp NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE TOURNAMENT(	
	TOU_ID decimal(16) PRIMARY KEY NOT NULL,
	NAME varchar2(128) NOT NULL,
	TEAM_NUMBER_LIMIT decimal(3) NOT NULL,
	DEB_FOR_ID decimal(16) NOT NULL,
	DATE_FROM timestamp NOT NULL,
	DATE_UNTIL timestamp NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE RESULT(	
	REZ_ID decimal(16) PRIMARY KEY NOT NULL,
	TOU_ID decimal(16) NOT NULL,
	DEB_ID decimal(16) NOT NULL,
	TEA_ID decimal(16) NOT NULL,
	JUD_ID decimal(16) NOT NULL,
	ROUND varchar2(32) NOT NULL,
	POINTS decimal(100) NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE COACH(	
	COA_ID decimal(16) PRIMARY KEY NOT NULL,
	NAME varchar2(128) NOT NULL,
	TEA_ID decimal(16) NOT NULL,
	DATE_OF_BIRTH timestamp,
	ADDRESS varchar2(128),
	TELEPHONE_NO varchar2(32),
	DATE_FROM timestamp NOT NULL,
	DATE_UNTIL timestamp NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE DEBATE_FORMAT(	
	DEB_FOR_ID decimal(16) PRIMARY KEY NOT NULL,
	FORMAT_NAME varchar2(64) NOT NULL,
	NO_OF_SPEAKERS decimal(3) NOT NULL,
	ROUND_NO decimal(2) NOT NULL,
	USER_LOCK timestamp NOT NULL);
	
CREATE TABLE JUDGE_NO_TOURNAMENT(	
	JUD_NO_TOU_ID decimal(16) PRIMARY KEY NOT NULL,
	JUD_ID decimal(16) NOT NULL,
	TOU_ID decimal(16) NOT NULL,
	ROUND varchar2(32) NOT NULL);

